In [1]:
import pandas as pd
import logging
import time
from utils.extract import extract_data

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Test the extraction with a small sample
print("Testing extraction with a small sample...")
start_time = time.time()

# Extract just 1 page and max 10 products
sample_data = extract_data(max_pages=1, max_products=10)

# Print results
print(f"Extraction completed in {time.time() - start_time:.2f} seconds")
print(f"Extracted {len(sample_data)} products")
print("\nSample data preview:")
print(sample_data.head())


print("Sample data saved to sample_data.csv")

2025-05-16 08:41:13,495 - INFO - Starting data extraction process

Testing extraction with a small sample...

Scraping pages: 0it [00:00, ?it/s]

2025-05-16 08:41:13,511 - INFO - Fetching page 1 from https://fashion-studio.dicoding.dev
/root/workspace/repos/dicoding-courses-final-project-archive/learn_fundamental_data_engineering/.dicoding-lfde-venv/lib/python3.11/site-packages/soupsieve/css_parser.py:876: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028
2025-05-16 08:41:13,748 - INFO - Scraped 10 products so far
2025-05-16 08:41:14,753 - INFO - Extraction completed. 10 products extracted.
2025-05-16 08:41:14,754 - INFO - Extraction took 1.26 seconds.

Extraction completed in 1.26 seconds
Extracted 10 products

Sample data preview:
             Title    Price                        Rating    Colors  \
0  Unknown Product  $100.00  Rating: ⭐ Invalid Rating / 5  5 Colors
1        T-shirt 2  $102.15             Rating: ⭐ 3.9 / 5  3 Colors
2         Hoodie 3  $496.88             Rating: ⭐ 4.8 / 5  3 Colors
3          Pants 4  $467.31             Rating: ⭐ 3.3 / 5  3 Colors
4      Outerwear 5  $321.59             Rating: ⭐ 3.5 / 5  3 Colors

        Size          Gender                  timestamp
0    Size: M     Gender: Men 2025-05-16 08:41:13.744359
1    Size: M   Gender: Women 2025-05-16 08:41:13.744884
2    Size: L  Gender: Unisex 2025-05-16 08:41:13.745341
3   Size: XL     Gender: Men 2025-05-16 08:41:13.745786
4  Size: XXL   Gender: Women 2025-05-16 08:41:13.746245
Sample data saved to sample_data.csv

In [2]:
sample_data

,Title,Price,Rating,Colors,Size,Gender,timestamp
0,Unknown Product,$100.00,Rating: ⭐ Invalid Rating / 5,5 Colors,Size: M,Gender: Men,2025-05-16 08:41:13.744359
1,T-shirt 2,$102.15,Rating: ⭐ 3.9 / 5,3 Colors,Size: M,Gender: Women,2025-05-16 08:41:13.744884
2,Hoodie 3,$496.88,Rating: ⭐ 4.8 / 5,3 Colors,Size: L,Gender: Unisex,2025-05-16 08:41:13.745341
3,Pants 4,$467.31,Rating: ⭐ 3.3 / 5,3 Colors,Size: XL,Gender: Men,2025-05-16 08:41:13.745786
4,Outerwear 5,$321.59,Rating: ⭐ 3.5 / 5,3 Colors,Size: XXL,Gender: Women,2025-05-16 08:41:13.746245
5,Jacket 6,$153.37,Rating: ⭐ 3.3 / 5,3 Colors,Size: S,Gender: Unisex,2025-05-16 08:41:13.746758
6,Crewneck 7,$430.75,Rating: ⭐ 4.3 / 5,3 Colors,Size: M,Gender: Men,2025-05-16 08:41:13.747225
7,T-shirt 8,$487.66,Rating: ⭐ 3.1 / 5,3 Colors,Size: L,Gender: Women,2025-05-16 08:41:13.747662
8,Hoodie 9,$248.26,Rating: ⭐ 3.2 / 5,3 Colors,Size: XL,Gender: Unisex,2025-05-16 08:41:13.748092
9,Pants 10,$193.76,Rating: ⭐ 4.2 / 5,3 Colors,Size: XXL,Gender: Men,2025-05-16 08:41:13.748849

In [3]:
# Import the transform function
from utils.transform import transform_data

# Perform transformation on the sample data
print("Starting transformation on sample data...")
transform_start_time = time.time()

# Transform the sample data
transformed_sample = transform_data(sample_data)

# Print results
print(f"Transformation completed in {time.time() - transform_start_time:.2f} seconds")
print(f"Products after transformation: {len(transformed_sample)} (removed {len(sample_data) - len(transformed_sample)} invalid/duplicate records)")
print("\nTransformed data preview:")
print(transformed_sample.head())

# Compare before and after
print("\nComparison of data before and after transformation:")
print(f"Before: {sample_data.shape[0]} rows × {sample_data.shape[1]} columns")
print(f"After: {transformed_sample.shape[0]} rows × {transformed_sample.shape[1]} columns")

2025-05-16 08:41:14,817 - INFO - Starting data transformation process
2025-05-16 08:41:14,819 - INFO - Removed 1 rows with invalid titles
2025-05-16 08:41:14,820 - INFO - Removed 0 rows with unavailable prices
2025-05-16 08:41:14,825 - INFO - Removed 0 rows with invalid prices after conversion
2025-05-16 08:41:14,828 - INFO - Removed 0 rows with invalid ratings
2025-05-16 08:41:14,831 - INFO - Removed 0 rows with invalid colors
2025-05-16 08:41:14,833 - INFO - Removed 0 rows with invalid sizes
2025-05-16 08:41:14,835 - INFO - Removed 0 rows with invalid genders
2025-05-16 08:41:14,840 - INFO - Removed 0 duplicate rows
2025-05-16 08:41:14,841 - INFO - Transformation completed. Rows before: 10, Rows after: 9

Starting transformation on sample data...
Transformation completed in 0.03 seconds
Products after transformation: 9 (removed 1 invalid/duplicate records)

Transformed data preview:
         Title        Price  Rating  Colors Size  Gender  \
1    T-shirt 2  Rp1,634,400     3.9       3    M   Women
2     Hoodie 3  Rp7,950,080     4.8       3    L  Unisex
3      Pants 4  Rp7,476,960     3.3       3   XL     Men
4  Outerwear 5  Rp5,145,440     3.5       3  XXL   Women
5     Jacket 6  Rp2,453,920     3.3       3    S  Unisex

                   timestamp
1 2025-05-16 08:41:13.744884
2 2025-05-16 08:41:13.745341
3 2025-05-16 08:41:13.745786
4 2025-05-16 08:41:13.746245
5 2025-05-16 08:41:13.746758

Comparison of data before and after transformation:
Before: 10 rows × 7 columns
After: 9 rows × 7 columns

In [4]:
transformed_sample

,Title,Price,Rating,Colors,Size,Gender,timestamp
1,T-shirt 2,"Rp1,634,400",3.9,3,M,Women,2025-05-16 08:41:13.744884
2,Hoodie 3,"Rp7,950,080",4.8,3,L,Unisex,2025-05-16 08:41:13.745341
3,Pants 4,"Rp7,476,960",3.3,3,XL,Men,2025-05-16 08:41:13.745786
4,Outerwear 5,"Rp5,145,440",3.5,3,XXL,Women,2025-05-16 08:41:13.746245
5,Jacket 6,"Rp2,453,920",3.3,3,S,Unisex,2025-05-16 08:41:13.746758
6,Crewneck 7,"Rp6,892,000",4.3,3,M,Men,2025-05-16 08:41:13.747225
7,T-shirt 8,"Rp7,802,560",3.1,3,L,Women,2025-05-16 08:41:13.747662
8,Hoodie 9,"Rp3,972,160",3.2,3,XL,Unisex,2025-05-16 08:41:13.748092
9,Pants 10,"Rp3,100,160",4.2,3,XXL,Men,2025-05-16 08:41:13.748849

In [5]:
from utils.load import save_to_google_sheets

result = save_to_google_sheets(transformed_sample)
print(f"Upload successful: {result}")

2025-05-16 08:41:17,415 - INFO - Successfully saved 9 records to Google Sheets

Upload successful: True

In [6]:
from utils.load import save_to_postgresql

result = save_to_postgresql(transformed_sample)
print(f"Upload successful: {result}")

2025-05-16 08:41:20,544 - INFO - Deleting only records with matching titles from table fashion_products
2025-05-16 08:41:20,752 - INFO - Successfully saved 9 records to PostgreSQL table 'fashion_products'

Upload successful: True

In [7]:
from utils.load import save_to_postgresql

result = save_to_postgresql(transformed_sample, clear_table=True)
print(f"Upload successful with SQLAlchemy: {result}")

2025-05-16 08:41:21,180 - INFO - Deleting all existing data from table fashion_products
2025-05-16 08:41:21,388 - INFO - Successfully saved 9 records to PostgreSQL table 'fashion_products'

Upload successful with SQLAlchemy: True

In [8]:
transformed_sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 1 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Title      9 non-null      object
 1   Price      9 non-null      object
 2   Rating     9 non-null      float64
 3   Colors     9 non-null      int64
 4   Size       9 non-null      object
 5   Gender     9 non-null      object
 6   timestamp  9 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 576.0+ bytes